/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface BudgetTracker {
    }
    interface DestinationSearch {
    }
    interface ItineraryBuilder {
        /**
          * @default null
         */
        "lat": number | null;
        /**
          * @default null
         */
        "lon": number | null;
    }
    interface MapView {
        /**
          * @default null
         */
        "lat": number | null;
        /**
          * @default null
         */
        "lon": number | null;
    }
}
export interface DestinationSearchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDestinationSearchElement;
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLBudgetTrackerElement extends Components.BudgetTracker, HTMLStencilElement {
    }
    var HTMLBudgetTrackerElement: {
        prototype: HTMLBudgetTrackerElement;
        new (): HTMLBudgetTrackerElement;
    };
    interface HTMLDestinationSearchElementEventMap {
        "destinationSelected": any;
    }
    interface HTMLDestinationSearchElement extends Components.DestinationSearch, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDestinationSearchElementEventMap>(type: K, listener: (this: HTMLDestinationSearchElement, ev: DestinationSearchCustomEvent<HTMLDestinationSearchElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDestinationSearchElementEventMap>(type: K, listener: (this: HTMLDestinationSearchElement, ev: DestinationSearchCustomEvent<HTMLDestinationSearchElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDestinationSearchElement: {
        prototype: HTMLDestinationSearchElement;
        new (): HTMLDestinationSearchElement;
    };
    interface HTMLItineraryBuilderElement extends Components.ItineraryBuilder, HTMLStencilElement {
    }
    var HTMLItineraryBuilderElement: {
        prototype: HTMLItineraryBuilderElement;
        new (): HTMLItineraryBuilderElement;
    };
    interface HTMLMapViewElement extends Components.MapView, HTMLStencilElement {
    }
    var HTMLMapViewElement: {
        prototype: HTMLMapViewElement;
        new (): HTMLMapViewElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "budget-tracker": HTMLBudgetTrackerElement;
        "destination-search": HTMLDestinationSearchElement;
        "itinerary-builder": HTMLItineraryBuilderElement;
        "map-view": HTMLMapViewElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface BudgetTracker {
    }
    interface DestinationSearch {
        "onDestinationSelected"?: (event: DestinationSearchCustomEvent<any>) => void;
    }
    interface ItineraryBuilder {
        /**
          * @default null
         */
        "lat"?: number | null;
        /**
          * @default null
         */
        "lon"?: number | null;
    }
    interface MapView {
        /**
          * @default null
         */
        "lat"?: number | null;
        /**
          * @default null
         */
        "lon"?: number | null;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "budget-tracker": BudgetTracker;
        "destination-search": DestinationSearch;
        "itinerary-builder": ItineraryBuilder;
        "map-view": MapView;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "budget-tracker": LocalJSX.BudgetTracker & JSXBase.HTMLAttributes<HTMLBudgetTrackerElement>;
            "destination-search": LocalJSX.DestinationSearch & JSXBase.HTMLAttributes<HTMLDestinationSearchElement>;
            "itinerary-builder": LocalJSX.ItineraryBuilder & JSXBase.HTMLAttributes<HTMLItineraryBuilderElement>;
            "map-view": LocalJSX.MapView & JSXBase.HTMLAttributes<HTMLMapViewElement>;
        }
    }
}
